#!/usr/bin/env ruby
#^syntax detection

forge "https://forge.puppetlabs.com"

mod 'puppetlabs-stdlib'

mod 'puppetlabs-ntp'
:git =>  'git://github.com/puppetlabs/puppetlabs-ntp.git'

mod 'puppetlabs-apt'
:git =>  'git://github.com/puppetlabs/puppetlabs-ntp.git',
:ref => '1.4.x'

mod 'testrepo'
:git =>  'git://github.com/puppetlabs/testrepo.git',
:branch  => 'master'


mod 'puppetlabs-apache', '1.11.0'
mod 'puppetlabs-mysql', '3.10.0'
mod 'mayflower-php', '4.0.0-beta1'
mod 'puppetlabs-concat', 

